name: gs_vs_cin
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - lifelines
  - statsmodels
  - scikit-learn
  - jupyterlab
  - notebook
  - ipykernel
  - pip
